- drivers/zynqportal/zynqportal.c
misc.this_device->of_node is assigned
clk_get updated for connectal-xilinx-v2014.4 (linux 3.17.0)
> some updates for new zynq kernel

- cpp/portal.h
This allows us to add "-D__STDC_FORMAT_MACROS" to the command line when compiling.
> __STDC_FORMAT_MACROS only defined if not already defined

- scripts/bsvdepend.py
This fixes issues where a bsv file may include a file with a different suffix (like .defines)
> add all files in bsvpath to abspaths for path lookup

- scripts/topgen.py
This fixed a syntax error in the generated Top.bsv when my module has multiple vectors of MemReadClients in its interface.
> fixed bug in topgen.py with multiple portalReaders and portalWriters

- Makefile
- drivers/portalmem/portalmem.c
1. Checking if `libgmp.so.3` before cloning `libgmp.so.10` in `Makefile`.
2. The current kernel version of `Centos 7` is `3.10.0` in which `dma_buf_export` only takes a single argument.
> fix dma_buf_export for kernel version 3.10.0

- bsv/GetPutWithClocks.bsv
These fix a compilation error for the kc705g2 target.
> Specify clock and reset for mkProbes in GetPutWithClocks.bsv

- bsv/SyncAxisFifo32x8.bsv
I think this is a cleaner solution since mkSyncAxisFifo32x8 doesn't have clk or rst.
> Removed default clocks from SyncAxisFifo32x8.bsv

- scripts/connectal-synth-axiddr3.tcl
- tests/ddr_minimal/Ddr3Test.bsv
- tests/ddr_minimal/Makefile
- tests/ddr_minimal/synth-ip.tcl
- tests/ddr_minimal/testddr3.cpp
The previous ddr3 example is using ConnectalMem and is a bit complicated (4 clock domain crossing instead of 2). This one is simpler.
I also updated the version of the MIG controller to work with vivado 2016.4
> Fix version MIG controller, add minimal ddr example

- verilog/awsf1.sv
This can save about 38K LUTs. Also remove some unnecessary wires in the DRAM instantiation.
> Turn off DRAM B and D.

- examples/sdcard_spi/Makefile
It looks like PROJDIR is no longer defined by connectal so it causes this example to fail to compile. This change fixes it and .matches the other examples that use PINOUT_FILE.
> Removed PROJDIR variable from sdcard_spi Makefile

- doc/library/source/tools/makefilegen.rst
- scripts/makefilegen.py
This adds support for adding unmanaged implementation constraint files in Vivado with the flag ```--unmanaged-implconstraints```.
An unmanaged constraint file is an XDC file that is imported as a plain TCL file, and vivado will not try to add or remove constraints from the file. This allows for more of the TCL language to be included in the file such as foreach and if. As a side effect of this, some critical warnings in managed constraint files get promotes to errors in unmanaged constraint files, resulting in some builds failing if all constraint files are blindly set to unmanaged.
Unmanaged constraint files are read using the ```-unmanaged``` flag of the ```read_xdc``` command.
> Added unmanaged impl constraint option

- bsv/ConnectalBramFifo.bsv
- bsv/ConnectalClocks.bsv
- verilog/PositiveReset.v
- verilog/SyncReset.v
This fixes some clock domain crossing issues in PositiveReset.v and SyncReset.v. It also modifies some import BVI statements for reset inputs that don't need to be synchronized to a clock.
This was tested with the ```ddr_minimal``` test on vc707 with ```--mainclockperiod=32``` added to ```CONNECTALFLAGS```. Without this fix, I got the following timing constraints:
```
*** timing violation ***
Slack (VIOLATED) :        -2.109ns  (required time - arrival time)
Source:                 tile_0_lDdr3Test_ddr3Controller/mc/u_axiddr3_mig/u_memc_ui_top_axi/u_ui_top/ui_wr_data0/app_wdf_rdy_r_copy2_reg/C
(rising edge-triggered cell FDRE clocked by clk_pll_i  {rise@0.000ns fall@2.500ns period=5.000ns})
Destination:            tile_0_lDdr3Test_ddr3Controller/mc/u_axiddr3_mig/u_memc_ui_top_axi/u_ui_top/ …
```
> Some fixes for synchronizing reset signals across clock domains

- examples/echopy/testecho.py
- generated/scripts/importbvi.py
- jtag/dumptrace.py
- jtag/readll.py
- pcie/pcieflat
- pcie/tlp.py
- scripts/boardinfo.py
- scripts/bsv.filter
- scripts/bsvdepend.py
- scripts/bsvdependencies.py
- scripts/bsvpreprocess.py
- scripts/check-timing.py
- scripts/extract-bvi-schedule.py
- scripts/generate-constraints.py
- scripts/globalv.py
- scripts/makefilegen.py
- scripts/packagesource.py
- scripts/parse_qsf.py
- scripts/parse_xdc.py
- scripts/portal.py
- scripts/reorderbytes.py
- scripts/syntax.py
- tests/bluecheck_harness/harness.py
Hi,
I'm trying to play around with this on NixOS, and one of the things it doesn't have is `python` in `/usr/bin`, so I have patched up all I could find to `/usr/bin/env python`.
There are some more things which might break:
```
$ grep -r '/usr/bin/'|grep '/usr/bin/env' -v
Makefile:       if [ -f /usr/bin/yum ] ; then yum install gmp strace python-argparse python-ply python-gevent; else apt-get install libgmp10 strace python-ply python-gevent; fi
cpp/runpython.cpp:    statok = stat("/usr/bin/python", &statbuf);
debian/connectal.install:/usr/bin/pcieflat
debian/rules:#!/usr/bin/make -f
examples/gyro_simple/test_gyro.py:            octave_file.write("#! /usr/bin/octave --persist \nv = [");
scripts/Doxyfile:PERL_PATH              = /usr/bin/perl
tests/spikehw/README.md:    Running …
```
> More #!/usr/bin/env python

- README.md
The markdown wasn't always proper:
1. Code needs an empty line, and 4 spaces from the current indent (i.e. for indent within a numbered list it's 7 spaces)
2. Subsubsection underline-style ~~~~ doesn't work, that's for verbatim text (this is specific to GitHub Flavoured Markdown: https://github.github.com/gfm/#fenced-code-blocks)
> Update/fix README.md

- boardinfo/awsf1.json
- bsv/AwsF1Top.bsv
- scripts/Makefile.connectal.build
- scripts/aws/build.sh
- scripts/aws/encrypt.tcl
- scripts/makefilegen.py
This gives a Connectal project control over what its derived clock is, as well as the ability to change the main clock recipe. This mechanism is also general enough to mean that we can stop hard-coding a specific strategy and let the project pass whatever `-strategy` flag they want if DEFAULT isn't good enough.
> Allow AWS F1 projects to configure their own clocks

- scripts/aws/create_dcp_from_cl.tcl
We can't let them define their own strateiges, as the HDK's
aws_build_dcp_from_cl.sh wrapper validates -strategy, but this provides
equivalent functionality, whilst also allowing projects to easily
inherit defaults from the requested strategy.
> Allow projects to provide their own strategy overrides

- drivers/pcieportal/portal.c
This fires far too frequently and just fills up the logs very quickly
making it impossible to see anything else.
> Don't flood syslog with a message on every interrupt

- scripts/bsvdependencies.py
If it's fine to completely ignore `line(/xx/yy...), this simple fix should work.
> Make bsvdependencies.py ignore wired outputs of bsc preprocessor

- drivers/pcieportal/libxdma.c
This is a minimal implementation based on [1] that matches the existing
code style for handling the page crossing edge case. Previously only one
place in the code correctly handled adjacent descriptors crossing a page
boundary, but now that code is copied to the other relevant places too.
We hit this case when attempting to re-load ELF files after a few
attempts, at least with my CheriBSD image.
[1] https://github.com/Xilinx/dma_ip_drivers/pull/49
> libxdma.c: Bug fix Xilinx/dma_ip_drivers#48

- drivers/pcieportal/libxdma.c
- drivers/pcieportal/libxdma.h
- drivers/pcieportal/xdma_thread.c
Upstream has now fixed the descriptors crossing page boundaries issue in a
different way, so this removes that local diff. It also includes a bug fix for
running on systems with fewer than 8 cores.
> Update XDMA drivers to latest upstream version

- scripts/cppgen.py
This fixes a typo that prevents the parsing of typedefs like `TAdd#(5, SomeNumericType)` where `SomeNumericType` is another type, not a literal number.
> Fix key when getting typedef

- scripts/aws/synth_awsf1.tcl
This is useful for projects that want to add additional Xilinx IP, or other files not caught by the existing rudimentary read_verilog glob.
> AWS: Allow projects to add additional files

- drivers/pcieportal/cdev_ctrl.c
- drivers/pcieportal/portal.c
- drivers/pcieportal/xdma_mod.c
- drivers/portalmem/portalmem.c
The driver build failed on RHEL 8.3, this is workaround fix.
> Fix build fatal on RHEL8
